= Description des plugins =

== Liste des erreurs possibles sur le log de Jeedom ==

=== [ERROR][Requête] === 

La requête HTTP vers le Spark Core n'est réussi, le code d'erreur et la source disponible sur le log permettent de voir le soucis.

=== [ERROR][JSON] ===

Les fichiers JSON ne sont pas conformes.

Code d'erreur JSON

La requête HTTP vers le Spark Core n'est réussi, le code d'erreur et la source disponible sur le log permettent de voir le soucis.

Par exemple, l'accesToken

=== [ERROR][JSON] ===

Les fichiers JSON ne sont pas conformes

.Code d'erreur JSON

|=======================================================================================================
|Constante 					|Signification
|0 JSON_ERROR_NONE        	|Aucune erreur n'est survenue
|1 JSON_ERROR_DEPTH        	|La profondeur maximale de la pile a été atteinte
|2 JSON_ERROR_STATE_MISMATCH|JSON invalide ou mal formé     	
|3 JSON_ERROR_CTRL_CHAR		|Erreur lors du contrôle des caractères ; probablement un encodage incorrect
|4 JSON_ERROR_SYNTAX   		|Erreur de syntaxe
|5 JSON_ERROR_UTF8			|Caractères UTF-8 malformés, possiblement mal encodés
|=======================================================================================================
Pour plus d'informations, voir https://secure.php.net/manual/fr/function.json-last-error.php

=== [ERROR][Equipement] ===

Un équipement est manquant pour le fonctionnement du plugin, pour réparer ceci retourner sur la page de configuration et recréer les équipements annexes et sauvegarder la page.

=== [ERROR][Fichier] ===

Le dossier racoon/core/config contient deux fichiers JSON, equipement.json et commande.json.

Ces deux fichiers ne doivent pas être modifés.

Pour les récupérer, voir https://github.com/projetBTSMaisonIntelligente/racoon/tree/master/core/config

=== [ERROR][Config] ===

Les données de configuration des équipements et commandes n'ont pas été récupéré.

Soit sur la page de configuration, Device ID et accessToken du Spark Core n'ont pas été rempli et/ou enregistré

Soit sur la page de configuration, Device ID et accessToken du Spark Core n'ont pas été rempli et/ou enregistré

Soit les fichiers JSON de config ne sont pas utilisables pour la création des racoon et racoonCmd

=== [ERROR][Paramètres] ===

Les paramètres de la méthode ne sont pas conformes, activer les logs DEBUG dans les options JEEDOM pour voir l'appel des méthodes et ses paramètres

=== [ERROR][Traitement] === 

Le résultat de la requête sur le Spark Core n'est pas compatible avec le type de traitement à effectuer 

- Informations : correspond à un array sous la forme 

- Fil Pilote : correspond à un string de 7 caractères qui sont soit 'A' pour arrêt 'C' pour confort 'H' pour hors-gel 'E' pour économique 'D' pour délestage

- Teleinfo : correspond à un string sous forme JSON {"ADCO":16161,"ptec":12,"iisnt":""}

- Température : correspond à un double récupéré depuis le récepteur 433Mhz du Spark Core d'une température

= Retour INDEX =

include::index.asciidoc[]

=== [ERROR][Traitement] === 

Le résultat de la requête sur le Spark Core n'est pas compatible avec le type de traitement à effectuer 
Informations : correspond à un array sous la forme 
Fil Pilote : correspond à un string de 7 caractères qui sont soit 'A' pour arrêt 'C' pour confort 'H' pour hors-gel 'E' pour économique 'D' pour délestage
Teleinfo : correspond à un string sous forme JSON {"ADCO":16161,"ptec":12,"iisnt":""}

===[ERROR][FonctionSparkCore] === 
.Fonction Spark Core

SUCCES 0

FP_INCORRECT 1

.Fonction setFp()

- TAILLE_INCORRECT -1

- ORDRE_INCORRECT 2

- RADIATEUR_DELESTAGE 3

.Fonction setReg()

- TEMP_INCORRECT 2

- CONSIGNE_IMPROBABLE 3
 